language: node_js
node_js:
  - node
install:
  - yarn install
script:
  - yarn build
  
deploy:
  email: joyceleeya@gmail.com
  github-token: $GITHUB_TOKEN
  keep_history: true
  local-dir: dist # 推送到 GitHub Pages 的目錄
  name: yuanchi
  provider: pages
  skip-cleanup: true
  target_branch: gh-pages
  on:
    branch: master

branches:
  only:
    - master

notifications: # 在失敗的時候接收 email 通知
  email:
    on_failure: always # default: always